config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "about" => 'homes#about'
  get "map" => 'homes#map'
  get "search" => 'searches#search'
  get 'ranks/index'
  get '/dive/hashtag/:name' => 'dives#hashtag'

  devise_for :users, module: "users", :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dives do
    resources :dive_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get "quit"
      patch "out"
    end
  end

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]
  resources :ranks, only: [:index]
  resources :bookmarks, only: [:index]
end

app/models/dive.rb
class Dive < ApplicationRecord
  attachment :image

  belongs_to :user
  has_many :dive_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :hashtag_relations
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, length: { maximum: 17 }
  validates :body, presence: true
  validates :dive_point, presence: true
  validates :water_temperature, presence: true
  validates :maximum_depth, presence: true
  validates :season, presence: true
  validates :dive_shop, presence: true

  is_impressionable

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  # ハッシュタグに関して
  after_create do
    dive = Dive.find_by(id: id)
    # ハッシュタグに打ち込まれたハッシュタグを検出
    hashtags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    dive.hashtags = []
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の#を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      dive.hashtags << tag
    end
  end

  before_update do
    dive = Dive.find_by(id: id)
    dive.hashtags.clear
    hashtags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      dive.hashtags << tag
    end
  end

  # 通知機能に関して
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and dive_id = ? and action = ?", current_user.id, user_id, id, "favorite"])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(dive_id: id, visited_id: user_id, action: "favorite")
      # 自分の投稿に対するいいねの場合は通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save
    end
  end

  def create_notification_comment!(current_user, dive_comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = DiveComment.select(:user_id).where(dive_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, dive_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, dive_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, dive_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(dive_id: id, dive_comment_id: dive_comment_id, visited_id: visited_id, action: "comment")
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def new
    @dive = Dive.new
  end

  def create
    @dive = Dive.new(dive_params)
    @dive.user_id = current_user.id
    if @dive.save
      redirect_to dives_path
    else
      flash[:error] = '投稿に失敗しました。未記入の項目があります。'
      render :new
    end
  end

  def index
    @dives = Dive.includes(:user).order('id DESC').page(params[:page]).per(4)
  end

  def show
    @dive = Dive.find(params[:id])
    @dive_comment = DiveComment.new
    impressionist(@dive, nil, unique: [:impressionable_id, :ip_address])
  end

  def edit
    @dive = Dive.find(params[:id])
    unless @dive.user == current_user
      redirect_to dives_path
    end
  end

  def update
    @dive = Dive.find(params[:id])
    if @dive.update(dive_params)
      redirect_to dives_path
    end
  end

  def destroy
    @dive = Dive.find(params[:id])
    @dive.destroy
    redirect_to dives_path
  end

  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @dives = @tag.dives.order('dive_id DESC').includes(:user).page(params[:page]).per(4)
  end

  def search
    @results = @q.result.order('id DESC').page(params[:page]).per(4)
  end

  private

  def set_q
    @q = Dive.includes(:user).ransack(params[:q])
  end

  def dive_params
    params.require(:dive).permit(:image, :dive_point, :title, :body, :water_temperature, :maximum_depth, :season, :dive_shop)
  end
end

app/helpers/dives_helper.rb
module DivesHelper
  def render_with_hashtags(body)
    body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/dive/hashtag/#{word.delete("#")}" }.html_safe
  end
end

app/views/dives/_form.html.erb
<%= form_with model: dive, local: true do |f| %>

  <div class="form-group row", style="overflow: scroll;">
    <div class="col-4"><%= f.label :画像 %></div>
    <div class="col-8"><%= f.attachment_field :image %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :ポイント名 %></div>
    <div class="col-8"><%= f.text_field :dive_point, placeholder: "潜ったダイビングポイント", class: "form-control" %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :タイトル %></div>
    <div class="col-8"><%= f.text_field :title, placeholder: "１８文字以内", class: "form-control" %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :内容 %></div>
    <div class="col-8"><%= f.text_area :body, placeholder: "ここに内容を記述します", class: "form-control", rows: "5" %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :水温 %></div>
    <div class="col-8 d-flex flex-row"><%= f.select :water_temperature,[['１０℃以下' ], ['１０〜１３℃'],['１３〜１５℃'],['１５〜１８℃'],['１８〜２０℃'],['２０〜２３℃'],['２３〜２５℃'],['２５〜２８℃'],['２８〜３０℃'],['３０℃以上']], {prompt:'選択'}, class: "form-control" %></div>
  </div>

  <div class="form-group row mt-3">
     <div class="col-4"><%= f.label :潜水深度 %></div>
     <div class="col-8 d-flex flex-row"><%= f.select :maximum_depth, [['５〜７m' ], ['７〜１０m'],['１０〜１５m'],['１５〜２０m'],['２０〜２５m'],['２５〜３０m'],['３０〜３５m'],['３５m〜']], {prompt:'選択'}, class: "form-control" %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :時期 %></div>
    <div class="col-8 d-flex flex-row"><%= f.select :season, [['１月' ], ['２月'],['３月'],['４月'],['５月'],['６月'],['７月'],['８月'],['９月'],['１０月'],['１１月'],['１２月']], {prompt:'選択'}, class: "form-control" %></div>
  </div>

  <div class="form-group row mt-3">
    <div class="col-4"><%= f.label :利用したショップ %></div>
    <div class="col-8"><%= f.text_field :dive_shop, placeholder: "ダイビングショップ名 (セルフダイビング）", class: "form-control" %></div>
  </div>

  <div class="text-center mt-4">
    <%= f.submit "新規登録", class: "btn btn-success", style:"width:200px" %>
  </div>

<% end %>

app/views/dives/edit.html.erb
<h1 class="text-center mt-5">Edit Adventure 🤿</h1>

<div class="col-10 offset-1 mt-5">
  <%= form_with model: @dive, local: true do |f| %>

    <div class="form-group row", style="overflow: scroll;">
      <div class="col-4"><%= f.label :画像 %></div>
      <div class="col-8"><%= f.attachment_field :image %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :ポイント名 %></div>
      <div class="col-8"><%= f.text_field :dive_point, placeholder: "潜ったダイビングポイント", class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :タイトル %></div>
      <div class="col-8"><%= f.text_field :title, placeholder: "１８文字以内", class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :内容 %></div>
      <div class="col-8"><%= f.text_area :body, placeholder: "ここに内容を記述します", class: "form-control", rows: "5" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :水温 %></div>
      <div class="col-8"><%= f.select :water_temperature,[['１０℃以下' ], ['１０〜１３℃'],['１３〜１５℃'],['１５〜１８℃'],['１８〜２０℃'],['２０〜２３℃'],['２３〜２５℃'],['２５〜２８℃'],['２８〜３０℃'],['３０℃以上']], {prompt:'選択'}, class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :潜水深度 %></div>
      <div class="col-8"><%= f.select :maximum_depth, [['５〜７m' ], ['７〜１０m'],['１０〜１５m'],['１５〜２０m'],['２０〜２５m'],['２５〜３０m'],['３０〜３５m'],['３５m〜']], {prompt:'選択'}, class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :時期 %></div>
      <div class="col-8"><%= f.select :season, [['１月' ], ['２月'],['３月'],['４月'],['５月'],['６月'],['７月'],['８月'],['９月'],['１０月'],['１１月'],['１２月']], {prompt:'選択'}, class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :利用したショップ %></div>
      <div class="col-8"><%= f.text_field :dive_shop, placeholder: "ダイビングショップ名 (セルフダイビング）", class: "form-control" %></div>
    </div>

    <div class="text-center mt-5">
      <%= f.submit "更新", class: "btn btn-success mr-2", style: "width:120px" %>
      <%= link_to "削除", dive_path(@dive.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger", style:"width:120px" %>
    </div>

  <% end %>
</div>

app/views/dives/hashtag.html.erb
<h1 class="text-center mt-5">ハッシュタグ #<%= @tag.hashname %>・<%= @dives.count %>件</h1>

<div class="container col-md-6 mb-5">
  <div class="scroll-list jscroll">
    <div class="card-list-container pt-3 row">
      <% @dives.includes(:user).each do |dive| %>
        <div class="card mx-auto mt-4 shadow-lg">
          <%= link_to dive_path(dive) do %>
            <%= attachment_image_tag dive, :image, :fill, 300, 230 ,class:"card-img-top py-2 px-2";%>
          <% end %>
          <div class="card-body">
          <div class="text-center card-title">
            <div class="mb-2">
              <%= dive.created_at.strftime('%Y/%m/%d') %>
            </div>
            <%= attachment_image_tag dive.user, :profile_image, size: "25x25", class: "rounded-circle" %>
            <%= link_to dive.user.name, user_path(dive.user_id) %>
          </div>
          <div class="text-center card-title"><%= dive.title %></div>
          <div class="text-center card-title">❤️<%= dive.favorites.count %>　・　💬<%= dive.dive_comments.count %></div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @dives %>
  </div>
</div>

app/views/dives/index.html.erb
<h1 class="text-center mt-5">All Adventures 🤿</h1>

<%= search_form_for @q, url: search_dives_path do |f| %>
  <div class="mt-4">
    <div class="text-center">
      <%= f.search_field :title_cont, required: true, placeholder: "タイトルで検索！" %>
    </div>
    <div class="text-center">
      <%= f.submit '検索', class: "mt-3" %>
    </div>
  </div>
<% end %>

<div class="container col-md-6 mb-5">
  <div class="scroll-list jscroll">
    <div class="card-list-container pt-1 row">
      <% @dives.includes([:user]).each do |dive| %>
        <div class="card mx-auto mt-4 shadow-lg">
          <%= link_to dive_path(dive) do %>
            <%= attachment_image_tag dive, :image, :fill, 300, 230 ,class: "card-img-top py-2 px-2";%>
          <% end %>
          <div class="card-body">
          <div class="text-center card-title">
            <div class="mb-2">
              <%= dive.created_at.strftime('%Y/%m/%d') %>
            </div>
            <%= attachment_image_tag dive.user, :profile_image, size: "25x25", class: "rounded-circle" %>
            <%= link_to dive.user.name, user_path(dive.user_id) %>
          </div>
          <div class="text-center card-title"><%= dive.title %></div>
          <div class="text-center card-title">❤️<%= dive.favorites.count %>　・　💬<%= dive.dive_comments.count %></div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @dives %>
  </div>
</div>

app/views/dives/new.html.erb
<h1 class="text-center mt-5">New Adventure 🤿</h1>

<div class="text-center text-danger pt-2">
    <%= flash[:error] %>
</div>

<div class="col-10 offset-1 mt-4">
  <%= render 'form', dive: @dive %>
</div>

app/views/dives/search.html.erb
<h2 class="text-center mt-5"><%= @q.title_cont %>の検索結果・<%= @results.count %>件 🤿</h2>

<div class="container col-md-6 mb-5">
  <div class="scroll-list jscroll">
    <div class="card-list-container pt-3 row">
      <% @results.each do |dive| %>
        <div class="card mx-auto mt-4 shadow-lg">
          <%= link_to dive_path(dive) do %>
            <%= attachment_image_tag dive, :image, :fill, 300, 230 ,class:"card-img-top py-2 px-2";%>
          <% end %>
          <div class="card-body">
          <div class="text-center card-title">
            <div class="mb-2">
              <%= dive.created_at.strftime('%Y/%m/%d') %>
            </div>
            <%= attachment_image_tag dive.user, :profile_image, size: "25x25", class: "rounded-circle" %>
            <%= link_to dive.user.name, user_path(dive.user_id) %>
          </div>
          <div class="text-center card-title"><%= dive.title %></div>
          <div class="text-center card-title">❤️<%= dive.favorites.count %>　・　💬<%= dive.dive_comments.count %></div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @results %>
  </div>
</div>

app/views/dives/show.html.erb
<h1 class="text-center mt-5">Marine Adventure 🤿</h1>

<div id="dives" class="container">
  <div class="row mt-5">

    <div class="col-md-6 col-12 pl-5 order-2 mb-5">

      <div class="row">
        <div class="detail col-5">投稿日</div>
        <div class="answer col-7"><%= @dive.created_at.strftime('%Y/%m/%d') %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">ユーザーネーム</div>
        <div class="answer col-7"><%= link_to @dive.user.name, user_path(@dive.user_id) %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">ポイント名</div>
        <div class="answer col-7"><%= @dive.dive_point %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">内容</div>
        <div class="answer col-7"><%= render_with_hashtags(@dive.body) %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">水温</div>
        <div class="answer col-7"><%= @dive.water_temperature %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">潜水深度</div>
        <div class="answer col-7"><%= @dive.maximum_depth %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">時期</div>
        <div class="answer col-7"><%= @dive.season %></div>
      </div>

      <div class="row mt-3">
        <div class="detail col-5">利用したショップ</div>
        <div class="answer col-7"><%= @dive.dive_shop %></div>
      </div>

      <% if @dive.user == current_user %>
        <div class="text-right mt-4 pt-2">
          <%= link_to "編集する", edit_dive_path(@dive), class: "btn btn-success" %>
        </div>
      <% end %>

    </div>
    <div class="col-md-6 col-12 order-1">

      <%= attachment_image_tag @dive, :image, :fill, 500, 350, class: "image-wrapper" %>
      <div class="d-flex mt-3">
        <div id="favorite_btn_<%= @dive.id %>" class="mr-3">
          <%= render 'favorites/favorite', dive: @dive %>
        </div>

      <% if @dive.user.is_deleted == false %>
        <% if user_signed_in? %>
          <div class="mr-3">
            <i class="far fa-comments mr-1"></i><span id="dive_comment_count"><%= @dive.dive_comments.count %></span>
          </div>
        <% end %>
      <% end %>

      <div class="mr-3">
        <div id="bookmark_btn_<%= @dive.id %>">
          <%= render 'bookmarks/bookmark', dive: @dive %>
        </div>
      </div>

      <% if @dive.user.is_deleted == false %>
      <% if user_signed_in? %>
        <div>
          <i class="far fa-eye mr-1"></i><%= @dive.impressionist_count %>
        </div>
      <% end %>
      <% else %>
        <div class="out row text-danger">退会済みユーザーの投稿です。</div>
      <% end %>
    </div>
      <div id="dive_comments">
        <%= render 'dive_comments/comment', dive: @dive, dive_comment: @dive_comment %>
      </div>
      <% if @dive.user.is_deleted == false %>
        <% if user_signed_in? %>
        <div class="row mt-1">
          <div class="col-sm-4 mt-1">
          <%= form_with(model:[@dive, @dive_comment], remote: true) do |f| %>
            <%= f.text_field :comment,required: true, id: "dive_comment_form", placeholder: 'コメント', class: "round-pill form-control" %>
            <div class="mt-3 mb-5"><%= f.submit "送信する", class: "btn btn-success btn-sm" %></div>
          <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>