config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "about" => 'homes#about'
  get "map" => 'homes#map'
  get "search" => 'searches#search'
  get 'ranks/index'
  get '/dive/hashtag/:name' => 'dives#hashtag'

  devise_for :users, module: "users", :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dives do
    resources :dive_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get "quit"
      patch "out"
    end
  end

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]
  resources :ranks, only: [:index]
  resources :bookmarks, only: [:index]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    # 通知機能
    @user = User.find(params[:user_id])
    @user.create_notification_follow!(current_user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<div class="text-center">

  <td>フォロー数: <%= link_to user.followings.count, user_followings_path(user.id) %></td> ・
  <td>フォロワー数: <%= link_to user.followers.count, user_followers_path(user.id) %></td>

  <div class="mt-2">
    <% if user_signed_in? %>
      <% if current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-outline-secondary" do %><i class="fas fa-user-alt"></i> フォロー中<% end %><br/>
        <% else %>
          <%= link_to user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-outline-secondary" do %><i class="fas fa-user-alt"></i> フォローする<% end %><br/>
        <% end %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/relationships/create.js.erb
$("#follow_btn").html("<%= j(render("relationships/follow", user: @user)) %>");

app/views/relationships/destroy.js.erb
$("#follow_btn").html("<%= j(render("relationships/follow", user: @user)) %>");

app/views/relationships/followers.html.erb
<h2 class="text-center mt-5"><%= @user.name %>さんのフォロワー</h2>

<div class="text-center mt-5">
  <% @users.each do |user| %>
    <%= attachment_image_tag user, :profile_image, size: "50x50", class: "rounded-circle" %>
    <span style="font-size:18px;">
      <%= link_to user.name, user_path(user) %>
    </span>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<h2 class="text-center mt-5"><%= @user.name %>さんがフォローしているユーザー</h2>

<div class="text-center mt-5">
  <% @users.each do |user| %>
    <%= attachment_image_tag user, :profile_image, size: "50x50", class: "rounded-circle" %>
    <span style="font-size:18px;">
      <%= link_to user.name, user_path(user) %>
    </span>
  <% end %>
</div>