config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "about" => 'homes#about'
  get "map" => 'homes#map'
  get "search" => 'searches#search'
  get 'ranks/index'
  get '/dive/hashtag/:name' => 'dives#hashtag'

  devise_for :users, module: "users", :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dives do
    resources :dive_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get "quit"
      patch "out"
    end
  end

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]
  resources :ranks, only: [:index]
  resources :bookmarks, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(google_oauth2)

  attachment :profile_image

  has_many :dives, dependent: :destroy
  has_many :dive_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :following

  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, "follow"])
    if temp.blank?
      notification = current_user.active_notifications.new(visited_id: id, action: "follow")
      notification.save if notification.valid?
    end
  end

  def self.search(search, word)
    if search != ""
      @user = User.where("name LIKE ?", "%#{word}%")
    else
      redirect_to request.referer
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
  end

  def failure
    redirect_to request.referer
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save

      yield resource if block_given?
      if resource.persisted?
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end

      WelcomeMailer.with(user: resource).welcome_email.deliver_later

    else
      flash[:error] = '未入力の情報または入力された情報に誤りがあります。'
      redirect_to request.referer
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = '退会済みです。再度ご登録後にご利用ください。'
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_dives = @user.dives.order('id DESC').page(params[:page]).per(4)
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def quit
    @user = User.find(params[:id])
  end

  def out
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :profile, :diver_rank)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile_image.html.erb
<div class="col-md-6 text-center mx-auto pt-5 mb-5">
  <%= attachment_image_tag user, :profile_image, size: "300x300", class: "rounded-circle img-thumbnail" %><br/>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-5">Edit Profile 👤</h1>

<div class="col-8 offset-2 mt-5">
  <%= form_with model: @user, local: true do |f| %>

    <div class="form-group row", style="overflow: scroll;">
      <div class="col-4"><%= f.label :プロフィール画像 %></div>
      <div class="col-8"><%= f.attachment_field :profile_image %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :ユーザーネーム %></div>
      <div class="col-8"><%= f.text_field :name, class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :紹介文 %></div>
      <div class="col-8"><%= f.text_field :profile, class: "form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :ダイバーズランク %></div>
      <div class="col-8"><%= f.select :diver_rank,[['オープンウォーター' ], ['アドバンスド'],['レスキュー'],['マスター・スクーバ'],['ダイブマスター'],['インストラクター以上']], {prompt:'選択'}, class: "form-control" %></div>
    </div>

    <div class="text-center mt-5">
      <%= f.submit "更新", class: "btn btn-success", style: "width:120px" %>
      <%= link_to "退会する", quit_user_path, class: "btn btn-danger", style:"width:120px" %>
    </div>

  <% end %>
</div>

app/views/users/quit.html.erb
 <div class="col text-center">
    <h4 class="font-weight-bold mt-5">本当に退会しますか？</h4>

    <p class="my-5">
      退会すると、会員登録情報や<br>
      DMなどの全てがが閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>

    <div>
      <%= link_to "退会しない", edit_user_path ,class:"btn btn-dark mx-3" ,style:"width:150px"%>
      <%= link_to "退会する", out_user_path, method: :PATCH ,class:"btn btn-danger mx-3" ,style:"width:150px"%>
    </div>
  </div>

app/views/users/show.html.erb
<h1 class="text-center mt-5"><%= @user.name %> さんのProfile</h1>

<div class="container mt-5">
  <div class="row col-md-10 ml-1">

    <%= render 'profile_image', user: @user %>

    <div class="col-md-4">
      <table class="table table-bordered table-hover">
        <tbody class="text-center">
          <tr class="text-white bg-primary">
            <th>ユーザーネーム</th>
          </tr>
          <tr><td><%= @user.name %></td></tr>
          <tr class="text-white bg-primary">
            <th>紹介文</th>
          </tr>
          <tr><td><%= @user.profile %></td></tr>
          <tr class="text-white bg-primary">
            <th>ダイバーズランク</th>
          </tr>
          <tr><td><%= @user.diver_rank %></td></tr>
          <tr class="text-white bg-primary">
            <th>投稿数</th>
          </tr>
          <tr><td><%= @user.dives.count %></td></tr>
        </tbody>
      </table>

      <% if @user.is_deleted == false %>

        <div id="follow_btn">
          <%= render 'relationships/follow', user: @user %>
        </div>

        <% if user_signed_in? %>
          <% if current_user != @user %>
          <div class="text-center mt-3">
            <%= link_to 'ダイレクトメッセージへ', chat_path(@user.id), class: "btn btn-primary" %>
          </div>
          <% end %>
        <% end %>

        <% if @user == current_user %>
        <div class="text-center mt-5">
          <%= link_to "編集する", edit_user_path, class: "btn btn-success" %>
        </div>
        <div class="text-center mt-3">
          <%= link_to "ブックマーク一覧", bookmarks_path, class: "btn btn-secondary" %>
        </div>
        <% end %>

        <% end %>

        <% if @user.is_deleted == true %>
        <div class="text-center mt-5">
          <h8 class="text-danger">このユーザーは退会済みです。</h8>
        </div>

      <% end %>

    </div>
  </div>
</div>

<div class="container col-md-6 mt-3 mb-5">
  <div class="card-list-container pt-3 row">
    <% @user_dives.each do |dive| %>
      <div class="card mx-auto mr-2 mt-4 shadow-lg">
        <%= link_to dive_path(dive) do %>
          <%= attachment_image_tag dive, :image, :fill, 300, 230 ,class:"card-img-top py-2 px-2";%>
        <% end %>
        <div class="card-body">
        <div class="text-center card-title">
          <div class="mb-2">
            <%= dive.created_at.strftime('%Y/%m/%d') %>
          </div>
          <%= attachment_image_tag dive.user, :profile_image, size: "25x25", class: "rounded-circle" %>
          <%= link_to dive.user.name, user_path(dive.user_id) %>
        </div>
        <div class="text-center card-title"><%= dive.title %></div>
        <div class="text-center card-title">❤️<%= dive.favorites.count %>　・　💬<%= dive.dive_comments.count %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>