config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "about" => 'homes#about'
  get "map" => 'homes#map'
  get "search" => 'searches#search'
  get 'ranks/index'
  get '/dive/hashtag/:name' => 'dives#hashtag'

  devise_for :users, module: "users", :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dives do
    resources :dive_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get "quit"
      patch "out"
    end
  end

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]
  resources :ranks, only: [:index]
  resources :bookmarks, only: [:index]
end

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to "サイト概要", about_path, data:{"turbolinks" => false} %>
  </li>
  <li>
    <%= link_to "マップ検索", map_path, data:{"turbolinks" => false} %>
  </li>
  <li>
    <%= link_to "マイページ", user_path(current_user.id) %>
  </li>
  <li>
    <%= link_to "ランキング", ranks_path %>
  </li>
  <li>
    <%= link_to "通知一覧", notifications_path %>
  </li>
  <li>
    <%= link_to "ブックマーク一覧", bookmarks_path %>
  </li>
  <li>
    <%= link_to "新規投稿", new_dive_path %>
  </li>
  <li>
    <%= link_to "投稿一覧", dives_path %>
  </li>
  <li>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  </li>
<% else %>
  <li>
    <%= link_to "サイト概要", about_path, data:{"turbolinks" => false} %>
  </li>
  <li>
    <%= link_to "マップ検索", map_path, data:{"turbolinks" => false} %>
  </li>
  <li>
    <%= link_to "ランキング", ranks_path %>
  </li>
  <li>
    <%= link_to "投稿一覧", dives_path %>
  </li>
  <li>
    <%= link_to "新規登録", new_user_registration_path %>
  </li>
  <li>
    <%= link_to "ログイン", new_user_session_path %>
  </li>
<% end %>

<%= render 'searches/search_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsDiveee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/">
            </span>
            <div class="logo">Let's Diveee!!!</div>
          </a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="mt-1 mr-3">
                  <%= link_to notifications_path do %>
                    <% if unchecked_notifications.any? %>
                    <span class="fa-fw text-white">
                      <i class="fas fa-bell"></i>
                      <% if unchecked_notifications.exists? %>
                        <span class="rounded-circle text-center"><%= unchecked_notifications.count %></span>
                      <% end %>
                    </span>
                    <% else %>
                    <i class="fas fa-bell text-white"></i>
                    <% end %>
                  <% end %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light"  %>
                </li>
              <% else %>
                <li>
                  <%= link_to "新規登録", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>

            <span class="navbar-nav">
            <%= render 'searches/search_form' %>
            </span>

          </div>

           <div id="sp-menu">
            <ul>
              <%= render "layouts/sidebar" %>
            </ul>
          </div>

          <div id="sidebar">
            <span class="menu-trigger">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>

        </div>
      </nav>
    </header>

    <%= yield %>
    <span id="back">
      <a href="">
        <%= image_tag asset_path('to-top.jpg'), data: {"turbolinks"=>false}, class: "arrow" %>
      </a>
    </span>

  </body>
</html>